apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 6 # alternatively can use kubectl scale --replicas=<num> replicaset myapp-rs
  # major difference between replicacollector and replicaset
  # replicaset allows us to manage pods under the rs not just by the template, but other pods as well
  selector: # REQUIRED
    matchLabels:
      type: frontend
