name: Tag Bump Action
description: Bump the version tag of the repository
inputs:
  token:
    description: 'GitHub token to push the tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ inputs.token }} 
    
    - name: Create release
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Latest tag is: $latest_tag"
        gh release create "$latest_tag" --title "Release $latest_tag" --notes "Release notes for $latest_tag" --generate-notes
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
