apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v2.8.0 
          name: mealie
          ports:
            - containerPort: 9000

# To test the port, I ran the following - k port-forward pods/mealie-xxxxx-xxxxx 9000:9000
