name: 'CI Workflow'
on:
  push:
    branches-ignore:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Pre-Commit Hooks
        uses: ./github-actions/pre-commit
