name: Bump Version Workflow
description: This workflow bumps the version of the repository and pushes a new tag.

on:
  workflow_dispatch:

permissions:
  contents: write  # Required to push tags
  id-token: write  # Required for GitHub Actions to authenticate

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: ./github-actions/tag-bump
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
